import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
//IMPORTING HELPER COMPONENTS
import ToastProvider from './components/ToastProvider';
import StoreProvider from './StoreProvider';
import AppProvider from './context/AppContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title:
    'Ninja Kitchen - Blenders, Kitchen Apppliances | Blenders, Air Fryers, Grills & More',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiase`}
      >
        <ToastProvider />
        <AppProvider>
          <StoreProvider> {children}</StoreProvider>
        </AppProvider>
      </body>
    </html>
  );
}
